apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1 
  labels:
    app: app1 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app1 
  template:
    metadata:
      labels:
        app: app1 
    spec:
      containers:
      - name: app1 
        image: carlosfalcone/projeto2-backfront:%TAG_BACKFRONT%
        imagePullPolicy: Always
        ports:
        - containerPort: 80


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: carlosfalcone/projeto2-database:%TAG_DATABASE%
        args:
        - "--ignore-db-dir=lost+found"
        imagePullPolicy: Always
        name: mysql
        ports:
        - containerPort: 3306
          name: mysql
        
        # Linhas abaixo introduzidas para implementaçao do PV e PVC
        
        env:
          # Use secret in real usage
        - name: MYSQL_ROOT_PASSWORD
          value: Senha123
        - name: MYSQL_DATABASE
          value: meubanco
        # Se for usar secrets, tem que gerar um arquivo secrets.yml para rodar no computador fisico local, pois este codigo de deployment está sendo executado no computador fisico local. O secret do github actions nao tem nenhuma ação sobre esse script, pois ele roda somente no computador remoto do github ou precisa conceder acesso ao computador que ele ira acessar para rodar os comandos.

        volumeMounts:
        - name: local
          mountPath: /var/lib/mysql
      volumes:
      - name: local
        persistentVolumeClaim:
          claimName: local

---
apiVersion: v1 
kind: PersistentVolume
metadata:
  name: local
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /meubanco/

---
apiVersion: v1 
kind: PersistentVolumeClaim
metadata:
  name: local
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi

---
apiVersion: v1
kind: Service
metadata:
  name: mysql-connection
spec:
  ports:
  - port: 3306
  selector:
    app: mysql
  clusterIP: None
