apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1 
  labels:
    app: app1 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app1 
  template:
    metadata:
      labels:
        app: app1 
    spec:
      containers:
      - name: app1 
        image: carlosfalcone/projeto2-backfront:1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 80


---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-dados3
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard-rwo

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: carlosfalcone/projeto2-database:1.0
        args:
        - "--ignore-db-dir=lost+found"
        imagePullPolicy: Always
        name: mysql
        ports:
        - containerPort: 3306
          name: mysql

        volumeMounts:
        - name: mysql-dados3
          mountPath: /var/lib/mysql/
      volumes:
      - name: mysql-dados3
        persistentVolumeClaim:
          claimName: mysql-dados3
            
      # env: # Bloco alterado para usar o secrets do github actions
      #   - name: MYSQL_ROOT_PASSWORD
      #     valueFrom:
      #       secretKeyRef:
      #         name: {{ secrets.MYSQL_ROOT_PASSWORD }} 
      #         key: MYSQL_ROOT_PASSWORD
          
      #   - name: MYSQL_DATABASE
      #     valueFrom:
      #       secretKeyRef:
      #         name: {{ secrets.MYSQL_DATABASE }} 
      #         key: MYSQL_DATABASE

---
apiVersion: v1
kind: Service
metadata:
  name: mysql-connection
spec:
  ports:
  - port: 3306
  selector:
    app: mysql
  clusterIP: None