name: Build and Deploy Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-qemu-action@v1

    - name: Docker Login
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Docker build and push
      env:
        DOCKER_TLS_CERTDIR: "/certs"
      run: |
        echo "Criando as imagens..."
        docker build -t carlosfalcone/projeto2-backfront:4.0 app/.
        docker build -t carlosfalcone/projeto2-database:1.0 database/. 

        echo "Realizando o push das imagens..."
        docker push carlosfalcone/projeto2-backfront:4.0
        docker push carlosfalcone/projeto2-database:1.0 


  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v2

    - name: Configurar PowerShell
      uses: microsoft/setup-powershell@v1.0.0

    - name: Executar script PowerShell
      run: |
        # Seu script PowerShell aqui
        Write-Host "Olá, GitHub Actions!"
